### ISSUE TITLE
What happened to the Calamity Remix Addon?

### ISSUE THREAD

**Issue by Totofer77** [GinYuH/CalValPlus#1]
Hello, I just want to ask you What happened to the Calamity Community Remix Mod, What was the reason that you deleted the Mod. 

What tells me that the mod existed is a link that came from : 
https://calamitymod.fandom.com/wiki/Community_modifications#Add-on_Mods

This one to be more precise: 
https://github.com/GinYuH/CalRemix

Is it okay if you at least give me an Explanation to this, I'm not mad or anything, I'm just curious. By the way, it's cool you've made the "Hypnos" Mod a real thing

**Comment by GinYuH** [comment]
it's not out yet lol
